language: python
python:
    - "3.8"

services:
    - postgresql

before_script:
    - psql -c 'create database test_db;' -U postgres

env:
    - export DJANGO_SECRET_KEY='SecretKeyForUseOnTravis'
    - export DJANGO_ALLOWED_HOSTS='127.0.0.1'
    - export DJANGO_SQL_ENGINE='django.db.backends.postgresql'
    - export DJANGO_SQL_DATABASE='test_db'

install:
    - pipenv install
    - pipenv install psycopg2

script:
    pipenv run python manage.py test