language: python
python:
    - "3.8"
services:
    - docker

before_install:
    - docker build -t jcchac/django-docker -f Dockerfile.dev .

script:
    - docker run jcchac/django-docker python manage.py test