version: '3.8'

services:
    db:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    web:
        build: ./
        command: gunicorn dockerizing_django.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on: 
            - db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static
        ports: 
            - 1337:80
        depends_on: 
            - web

volumes:
    postgres_data:
    static_volume: